### ISSUE TITLE
Assistance

### ISSUE THREAD

**Issue by zmesser** [Amin-0-1/hackintosh-Dell-g3-15-3590-#22]
Hello, I am very interested in trying to install Mojave or any other version of OS X on my g3 3590.  I am not new to Mac OS or installing it with recovery mode or external boot efi but I am completely unsure of how to compile the files in order to create a bootable disk.  Are the files in this directory somehow combined with a mac os iso or bootable img?  I know this is a very novice question but any help would be greatly appreciated.  Thank You.

**Comment by Mihaidev-cloud** [comment]
Hey I tried too, to install the mojave with the same efi but mine appears access denied logo which it means after made I read all forums it means is not supported because the software it detects macbook pro 19 because of smbios which is like masking the original smbios of laptop. I hope I could help you if you find any solutions how to do it, tell me!

**Comment by Amin-0-1** [comment]
I've susccessfully installed MacOS Montery, I'll upload the new OC files today, keep in touch pros
